import SideBar from "@/components/SideBar/SideBar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <SideBar />
      <main className="flex flex-col w-full h-screen gap-2">
        <header className="flex items-center h-12 shrink-0 px-4 border-b">
          <SidebarTrigger />
        </header>
        <div className="flex flex-col flex-1 p-4 pt-0 w-full overflow-auto">
          {children}
        </div>
      </main>
    </SidebarProvider>
  );
}
